// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-04-18 10:23:51.137289 -0300 -03 m=+0.039095104

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Marcelo Cabezas",
            "email": "mcabezas@outlook.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/games": {
            "post": {
                "description": "Creates a new game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Creates a new game",
                "operationId": "Games",
                "parameters": [
                    {
                        "description": "Create Game input",
                        "name": "CreateParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/restapi.CreateGameResponse"
                        }
                    }
                }
            }
        },
        "/games/{game_id}": {
            "get": {
                "description": "Retrieves a Game by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Game",
                "operationId": "Games",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "game_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.GetGameResponse"
                        }
                    }
                }
            }
        },
        "/games/{game_id}/cells/{row}/{column}": {
            "patch": {
                "description": "Reveal a Cell if it is available for that",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cell"
                ],
                "summary": "Patch a Cell",
                "operationId": "Cell",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "game_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Row",
                        "name": "row",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Columns",
                        "name": "column",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.RevealCellResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "restapi.CreateGameRequest": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "integer"
                },
                "rows": {
                    "type": "integer"
                }
            }
        },
        "restapi.CreateGameResponse": {
            "type": "object",
            "properties": {
                "gameID": {
                    "type": "string"
                }
            }
        },
        "restapi.GetGameResponse": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "integer"
                },
                "gameID": {
                    "type": "string"
                },
                "requestID": {
                    "type": "string"
                },
                "rows": {
                    "type": "integer"
                }
            }
        },
        "restapi.RevealCellResponse": {
            "type": "object",
            "properties": {
                "hasMine": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:5000",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Minesweeper Go Restful API",
	Description: "Minesweeper API implementation",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
