basePath: /
definitions:
  restapi.CreateGameRequest:
    properties:
      columns:
        type: integer
      rows:
        type: integer
    type: object
  restapi.CreateGameResponse:
    properties:
      gameID:
        type: string
    type: object
  restapi.FlagResponse:
    properties:
      requestID:
        type: string
    type: object
  restapi.GetGameResponse:
    properties:
      gameID:
        type: string
      requestID:
        type: string
    type: object
  restapi.RevealCellResponse:
    properties:
      mine:
        type: boolean
      near_mines:
        type: integer
    type: object
host: localhost:5000
info:
  contact:
    email: mcabezas@outlook.com
    name: Marcelo Cabezas
  description: Minesweeper API implementation
  license: {}
  title: Minesweeper Go Restful API
  version: "1.0"
paths:
  /games:
    post:
      consumes:
      - application/json
      description: Creates a new game
      operationId: Games
      parameters:
      - description: Create Game input
        in: body
        name: CreateParams
        required: true
        schema:
          $ref: '#/definitions/restapi.CreateGameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/restapi.CreateGameResponse'
      summary: Creates a new game
      tags:
      - Games
  /games/{game_id}:
    get:
      consumes:
      - application/json
      description: Retrieves a Game by ID
      operationId: Games
      parameters:
      - description: Game ID
        in: path
        name: game_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/restapi.GetGameResponse'
      summary: Game
      tags:
      - Games
  /games/{game_id}/cells/{row}/{column}:
    patch:
      consumes:
      - application/json
      description: Reveal a Cell if it is available for that
      operationId: Cell
      parameters:
      - description: Game ID
        in: path
        name: game_id
        required: true
        type: string
      - description: Row
        in: path
        name: row
        required: true
        type: integer
      - description: Columns
        in: path
        name: column
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/restapi.RevealCellResponse'
      summary: Patch a Cell
      tags:
      - Cell
  /games/{game_id}/cells/{row}/{column}/flag:
    delete:
      consumes:
      - application/json
      description: Remove a flag from a specific cell
      operationId: Cell
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/restapi.FlagResponse'
        "204": {}
        "403": {}
        "500": {}
      summary: Remove a flag from a specific cell
      tags:
      - Cell
    post:
      consumes:
      - application/json
      description: Put a flag into a specific cell
      operationId: Cell
      produces:
      - application/json
      responses:
        "200": {}
        "204": {}
        "403": {}
        "500": {}
      summary: Puts a flag into a specific cell
      tags:
      - Cell
swagger: "2.0"
